### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by shawshuai** [compose-museum/compose-library#163]
- `快速入门`板块中`在 Android Studio 中预览你的函数`第二段正文` **因为新的 previewGreeting() 函数并没有在任何地方被调用** `中` **previewGreeting()** `应该为`**PreviewGreeting()**` (大写）
- `快速入门`板块中`2. 第二步：界面`下第一行`Compose`的e字母没有正确显示在md格式内。
（都不是什么问题）

**Comment by RugerMcCarthy** [comment]
感谢提出Issue，问题已修复
