### ISSUE TITLE
请问这个描述是什么意思？

### ISSUE THREAD

**Issue by q4x3** [compose-museum/compose-library#180]
“Composable 通常采取一个 content 的 Composable ，lambda(content: @Composable () -> Unit)”这一段看的不是很明白..或许有更合适一点的表达方式吗？

**Comment by Nthily** [comment]
hi，请问一下是在哪个地方的？

**Comment by q4x3** [comment]
https://docs.compose.net.cn/layout/overview/ 概述中“基于插槽的布局”那部分

**Comment by Nthily** [comment]
"Composable 通常会采取一个 `content` (具有 @Composable 函数的 lambda 表达式)" `content: @Composable () -> Unit`. 而在根据特定的用途，公开多个 `content`, 例如 `TopAppBar` 这个 `Composable` 可以提供 `actions` `title` `navigationIcon` 等

**Comment by Nthily** [comment]
感谢指出！这章还是做的有点不太好

**Comment by q4x3** [comment]
感谢！大概明白了。想请问一下有更方便一些的联系方式吗？暑期课设做安卓app，想尝试一下使用jetpack compose开发，预计还会有很多问题XD

**Comment by Nthily** [comment]
咱🚪有个微信的交流群，你可以先加俺 qq， 736089512
